# Generated by Django 2.0.1 on 2019-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_api_html_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=40, null=True)),
                ('faculty', models.CharField(max_length=40, null=True)),
                ('timings', models.CharField(max_length=40, null=True)),
                ('duration', models.CharField(max_length=40, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
